arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
  - SwingR_rev
  - SwingL_rev

gazebo_ros_control:
  pid_gains:
    SwingR_rev: {p: 100.0, i: 0.01, d: 10.0}
    SwingL_rev: {p: 100.0, i: 0.01, d: 10.0}