# velocity Controllers ---------------------------------------
WheelL_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: WheelL_cont
  pid: {p: 300.0, i: 1.0, d: 0.0}

WheelR_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: WheelR_cont
  pid: {p: 300.0, i: 1.0, d: 0.0}